version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "80:80"
    environment:
      - DATABASE=db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
